# Generated by Django 5.1.3 on 2024-11-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_description_product_key_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warrant_months',
            field=models.IntegerField(default=0),
        ),
    ]
